version: '3'
services:
  web:
    build: ./rails_api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DUMMY_API_URL: http://dummy_api:3001
    ports:
      - "3000:3000"
    volumes:
      - ./rails_api:/usr/src/rspec_template
    links:
      - db
      - dummy_api

  db:
    image: mysql:5.7
    volumes:
      - ./rails_api/db_data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  dummy_api:
    build: ./dummy_api
    ports:
      - 3001:3001
    volumes:
      - ./dummy_api:/dummy_api
    command: json-server --watch db.json --host 0.0.0.0 --port 3001
